export const APP_GET_TABLE_LISTED = "appGetTableListed"
export const APP_PUT_DATA = "appPutData"
export const APP_PERSONEL = "appPersonel"
export const APP_POST_CODES_API_GET = "appPostCodesApiGet"
export const APP_POST_CODES_ADRESS = "appPostCodesAdress"