export const SET_TABLE_DATA = "setTableData"
export const SET_AGENT_DATA = "setAgentData"
export const SET_POST_CODE = "setPostCode"
export const SET_APP_ADRESS = "setAppAdress"
export const SET_CONTACT_ID = "setContactId"